columns:
  - person_age: float
  - person_gender: category
  - person_education: category
  - person_income: float
  - person_emp_exp: float
  - person_home_ownership: category
  - loan_amnt: float
  - loan_intent: category
  - loan_int_rate: float
  - loan_percent_income: float
  - cb_person_cred_hist_length: float
  - credit_score: int
  - previous_loan_defaults_on_file: category
  - loan_status: int

numerical_columns:
  - person_age
  - person_income
  - person_emp_exp
  - loan_amnt
  - loan_int_rate
  - loan_percent_income
  - cb_person_cred_hist_length
  - credit_score

categorical_columns:
  - person_gender
  - person_education
  - person_home_ownership
  - loan_intent
  - previous_loan_defaults_on_file

drop_columns:
  - _id

transform_features:
  - person_age
  - person_income
  - person_emp_exp
  - cb_person_cred_hist_length

or_columns:
  - person_gender
  - previous_loan_defaults_on_file

oh_columns:
  - person_education
  - person_home_ownership
  - loan_intent
